# Generated by Django 2.2.4 on 2020-07-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='times',
            field=models.FloatField(default=0),
        ),
    ]
