# Generated by Django 2.2.4 on 2020-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0002_auto_20200728_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_name', models.CharField(max_length=50)),
                ('vacation_left_date', models.IntegerField()),
                ('vacation_date', models.IntegerField()),
                ('doucument_payment', models.IntegerField(default=0)),
            ],
        ),
    ]
