# Generated by Django 2.2.4 on 2020-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0003_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='used_vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_name', models.CharField(max_length=50)),
                ('vacation_date', models.IntegerField()),
                ('used_date', models.DateField()),
            ],
        ),
    ]
