# Generated by Django 2.2.4 on 2020-08-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0004_used_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memotitle', models.CharField(max_length=100)),
                ('memotext', models.CharField(max_length=1000)),
            ],
        ),
    ]
