# Generated by Django 2.2.4 on 2020-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0006_memo_memoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memotext',
            field=models.TextField(max_length=1000),
        ),
    ]
