# Generated by Django 2.2.4 on 2020-09-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0007_auto_20200825_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='dawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dawn_name', models.CharField(max_length=100)),
                ('find_check', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='evening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening_name', models.CharField(max_length=100)),
                ('find_check', models.IntegerField(default=0)),
            ],
        ),
    ]
