# Generated by Django 2.2.4 on 2020-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0008_dawn_evening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawn',
            name='find_check',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='evening',
            name='find_check',
            field=models.BooleanField(default=0),
        ),
    ]
