# Generated by Django 2.2.4 on 2020-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0009_auto_20200904_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawn',
            name='weekend',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='evening',
            name='weekend',
            field=models.IntegerField(default=7),
        ),
    ]
