# Generated by Django 2.2.4 on 2020-09-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0010_auto_20200914_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='memoid',
        ),
    ]
