# Generated by Django 2.2.4 on 2020-10-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0012_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileupload',
        ),
    ]
