# Generated by Django 2.2.4 on 2020-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0013_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_type',
            field=models.IntegerField(default=1),
        ),
    ]
