# Generated by Django 2.2.4 on 2020-11-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0014_vacation_vacation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='month',
            field=models.IntegerField(),
        ),
    ]
