# Generated by Django 2.2.4 on 2020-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0016_mileage_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='every',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every_name', models.CharField(max_length=100)),
                ('weekend', models.IntegerField(default=7)),
                ('find_check', models.BooleanField(default=False)),
            ],
        ),
    ]
