# Generated by Django 2.2.4 on 2020-12-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0017_every'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='every',
            name='weekend',
        ),
    ]
