# Generated by Django 2.2.4 on 2020-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hlist', '0018_remove_every_weekend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekend', models.IntegerField(default=7)),
                ('find_check', models.BooleanField(default=False)),
                ('checktype', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dawn',
        ),
        migrations.DeleteModel(
            name='evening',
        ),
        migrations.DeleteModel(
            name='every',
        ),
    ]
