# Generated by Django 2.2.4 on 2020-10-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(upload_to='mil'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
    ]
