# Generated by Django 2.2.4 on 2020-10-19 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20201008_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='uploaddate',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 10, 8, 39, 914457, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
