# Generated by Django 2.2.4 on 2020-10-22 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_uploadfilemodel_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
