# Generated by Django 2.2.4 on 2020-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_uploadfilemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
