# Generated by Django 2.2.4 on 2020-10-29 10:14

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_auto_20201029_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
