# Generated by Django 2.2.4 on 2020-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_uploadfilemodel_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='content',
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='제목'),
        ),
    ]
