# Generated by Django 2.2.4 on 2020-10-29 10:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_auto_20201029_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
