# Generated by Django 2.2.4 on 2020-10-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0008_auto_20201029_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='body',
            new_name='Ubody',
        ),
    ]
