# Generated by Django 2.2.4 on 2020-11-24 11:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0010_auto_20201102_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='제목')),
                ('file', models.FileField(upload_to='')),
                ('uploaddate', models.DateField(auto_now_add=True)),
                ('Ubody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
