# Generated by Django 2.2.4 on 2020-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0011_etcfilemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EtcFileModel',
            new_name='EtcUploadFileModel',
        ),
    ]
