# Generated by Django 2.2.4 on 2021-02-02 10:07

from django.db import migrations, models
import navbar.models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0012_auto_20201125_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcuploadfilemodel',
            name='file',
            field=models.FileField(storage=navbar.models.OverWriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(storage=navbar.models.OverWriteStorage(), upload_to=''),
        ),
    ]
